import { Player } from 'src/app/interfaces/players.interface';

export const PlayersDB: Player[] = [
  {
    id: 114492,
    name: 'Jussandro Pimenta Matos',
    firstname: 'Jussandro',
    lastname: 'Pimenta Matos',
    age: 29,
    birth: {
      date: '1992-03-11',
      place: 'Irecê',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '176 cm',
    weight: '64 kg',
    injured: false,
    photo: 'https://media-2.api-sports.io/football/players/114492.png',
  },
  {
    id: 10539,
    name: 'Jones Carioca',
    firstname: 'Jones',
    lastname: 'da Silva Lopes',
    age: 33,
    birth: {
      date: '1988-10-14',
      place: 'Caratinga',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '177 cm',
    weight: '74 kg',
    injured: false,
    photo: 'https://media-2.api-sports.io/football/players/10539.png',
  },
  {
    id: 114641,
    name: 'Alessandro  Faioli Amantino',
    firstname: 'Alessandro',
    lastname: 'Faioli Amantino',
    age: 36,
    birth: {
      date: '1980-08-01',
      place: 'Belo Horizonte',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '183 cm',
    weight: '82 kg',
    injured: false,
    photo: 'https://media-1.api-sports.io/football/players/114641.png',
  },
  {
    id: 77792,
    name: 'Elias Constantino Pereira Filho',
    firstname: 'Elias',
    lastname: 'Constantino Pereira Filho',
    age: 34,
    birth: {
      date: '1987-02-13',
      place: 'Campos',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '182 cm',
    weight: '78 kg',
    injured: false,
    photo: 'https://media-3.api-sports.io/football/players/77792.png',
  },
  {
    id: 114449,
    name: 'Jéferson Rodrigues Gonçalves',
    firstname: 'Jéferson',
    lastname: 'Rodrigues Gonçalves',
    age: 32,
    birth: {
      date: '1984-07-15',
      place: 'Brasília',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '180 cm',
    weight: '76 kg',
    injured: false,
    photo: 'https://media-2.api-sports.io/football/players/114449.png',
  },
  {
    id: 114557,
    name: 'Lucivaldo Lazaro de Abreu',
    firstname: 'Lucivaldo',
    lastname: 'Lazaro de Abreu',
    age: 38,
    birth: {
      date: '1983-08-22',
      place: 'Natal',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '179 cm',
    weight: '74 kg',
    injured: false,
    photo: 'https://media-2.api-sports.io/football/players/114557.png',
  },
  {
    id: 114676,
    name: 'José Alyson dos Santos Alves',
    firstname: 'José Alyson',
    lastname: 'dos Santos Alves',
    age: 31,
    birth: {
      date: '1990-06-13',
      place: 'Aracaju',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '183 cm',
    weight: '78 kg',
    injured: false,
    photo: 'https://media-3.api-sports.io/football/players/114676.png',
  },
  {
    id: 105220,
    name: 'Caio César Alves dos Santos',
    firstname: 'Caio César',
    lastname: 'Alves dos Santos',
    age: 35,
    birth: {
      date: '1986-05-29',
      place: 'Mirandópolis',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '186 cm',
    weight: '85 kg',
    injured: false,
    photo: 'https://media-1.api-sports.io/football/players/105220.png',
  },
  {
    id: 114648,
    name: 'José Kléberson Pereira',
    firstname: 'José',
    lastname: 'Kléberson Pereira',
    age: 43,
    birth: {
      date: '1979-06-19',
      place: 'Uraí',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '175 cm',
    weight: '63 kg',
    injured: false,
    photo: 'https://media-1.api-sports.io/football/players/114648.png',
  },
  {
    id: 114707,
    name: 'Lenine',
    firstname: 'Victor Lenine',
    lastname: 'Pereira Santana',
    age: 30,
    birth: {
      date: '1991-04-15',
      place: null,
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: null,
    weight: null,
    injured: false,
    photo: 'https://media-3.api-sports.io/football/players/114707.png',
  },
  {
    id: 114402,
    name: 'Helder',
    firstname: 'Helder',
    lastname: 'De Paula Santos',
    age: 37,
    birth: {
      date: '1984-06-20',
      place: 'Floriano',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '182 cm',
    weight: '82 kg',
    injured: false,
    photo: 'https://media-2.api-sports.io/football/players/114402.png',
  },
  {
    id: 53933,
    name: 'Omar',
    firstname: 'Omar Constante',
    lastname: 'Reis Santos',
    age: 32,
    birth: {
      date: '1989-01-22',
      place: 'Itatim',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '197 cm',
    weight: '89 kg',
    injured: false,
    photo: 'https://media-2.api-sports.io/football/players/53933.png',
  },
  {
    id: 114654,
    name: 'Ávine Júnior Cardoso',
    firstname: 'Ávine',
    lastname: 'Júnior Cardoso',
    age: 31,
    birth: {
      date: '1988-02-21',
      place: 'Aimores',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '171 cm',
    weight: '64 kg',
    injured: false,
    photo: 'https://media-1.api-sports.io/football/players/114654.png',
  },
  {
    id: 114710,
    name: 'Renan',
    firstname: 'Renan',
    lastname: 'Alves Florêncio',
    age: 28,
    birth: {
      date: '1993-03-19',
      place: null,
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: null,
    weight: null,
    injured: false,
    photo: 'https://media-1.api-sports.io/football/players/114710.png',
  },
  {
    id: 114496,
    name: 'Danny Bittencourt Morais',
    firstname: 'Danny',
    lastname: 'Bittencourt Morais',
    age: 36,
    birth: {
      date: '1985-06-29',
      place: 'Porto Alegre',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '187 cm',
    weight: '70 kg',
    injured: false,
    photo: 'https://media-3.api-sports.io/football/players/114496.png',
  },
  {
    id: 114725,
    name: 'Dudu',
    firstname: 'Eduardo Enrique',
    lastname: 'Ludwing',
    age: 29,
    birth: {
      date: '1992-04-09',
      place: 'Salvador',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '190 cm',
    weight: '85 kg',
    injured: false,
    photo: 'https://media-3.api-sports.io/football/players/114725.png',
  },
  {
    id: 80739,
    name: 'Leandro Fahel Matos',
    firstname: 'Leandro',
    lastname: 'Fahel Matos',
    age: 36,
    birth: {
      date: '1981-08-15',
      place: 'Teófilo Otoni',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '182 cm',
    weight: '81 kg',
    injured: false,
    photo: 'https://media-2.api-sports.io/football/players/80739.png',
  },
  {
    id: 88729,
    name: 'Neto',
    firstname: 'Darcy Dolce',
    lastname: 'Neto',
    age: 40,
    birth: {
      date: '1981-02-07',
      place: 'São José do Rio Preto',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '175 cm',
    weight: '67 kg',
    injured: false,
    photo: 'https://media-1.api-sports.io/football/players/88729.png',
  },
  {
    id: 114669,
    name: 'José Roberto De Oliveira',
    firstname: 'José Roberto',
    lastname: 'De Oliveira',
    age: 35,
    birth: {
      date: '1980-12-09',
      place: 'Itumbiara',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '170 cm',
    weight: '72 kg',
    injured: false,
    photo: 'https://media-2.api-sports.io/football/players/114669.png',
  },
  {
    id: 114468,
    name: 'Rodrigo de Souza Cardoso',
    firstname: 'Rodrigo',
    lastname: 'de Souza Cardoso',
    age: 36,
    birth: {
      date: '1982-03-04',
      place: 'Rio de Janeiro',
      country: 'Brazil',
    },
    nationality: 'Brazil',
    height: '183 cm',
    weight: '85 kg',
    injured: false,
    photo: 'https://media-1.api-sports.io/football/players/114468.png',
  },
];
