import { Team } from 'src/app/interfaces/teams.interface';

export const TeamsDB: Team[] = [
  {
    id: 118,
    name: 'Bahia',
    code: 'BAH',
    country: 'Brazil',
    founded: 1931,
    logo: 'https://media-3.api-sports.io/football/teams/118.png',
  },
  {
    id: 119,
    name: 'Internacional',
    code: 'INT',
    country: 'Brazil',
    founded: 1909,
    logo: 'https://media-3.api-sports.io/football/teams/119.png',
  },
  {
    id: 120,
    name: 'Botafogo',
    code: 'BOT',
    country: 'Brazil',
    founded: 1904,
    logo: 'https://media-1.api-sports.io/football/teams/120.png',
  },
  {
    id: 121,
    name: 'Palmeiras',
    code: 'PAL',
    country: 'Brazil',
    founded: 1914,
    logo: 'https://media-3.api-sports.io/football/teams/121.png',
  },
  {
    id: 123,
    name: 'Sport Recife',
    code: 'SPO',
    country: 'Brazil',
    founded: 1905,
    logo: 'https://media-1.api-sports.io/football/teams/123.png',
  },
  {
    id: 124,
    name: 'Fluminense',
    code: 'FLU',
    country: 'Brazil',
    founded: 1902,
    logo: 'https://media-3.api-sports.io/football/teams/124.png',
  },
  {
    id: 126,
    name: 'Sao Paulo',
    code: 'PAU',
    country: 'Brazil',
    founded: 1930,
    logo: 'https://media-2.api-sports.io/football/teams/126.png',
  },
  {
    id: 127,
    name: 'Flamengo',
    code: 'FLA',
    country: 'Brazil',
    founded: 1895,
    logo: 'https://media-2.api-sports.io/football/teams/127.png',
  },
  {
    id: 128,
    name: 'Santos',
    code: 'SAN',
    country: 'Brazil',
    founded: 1912,
    logo: 'https://media-1.api-sports.io/football/teams/128.png',
  },
  {
    id: 130,
    name: 'Gremio',
    code: 'GRE',
    country: 'Brazil',
    founded: 1903,
    logo: 'https://media-2.api-sports.io/football/teams/130.png',
  },
  {
    id: 131,
    name: 'Corinthians',
    code: 'COR',
    country: 'Brazil',
    founded: 1910,
    logo: 'https://media-3.api-sports.io/football/teams/131.png',
  },
  {
    id: 133,
    name: 'Vasco DA Gama',
    code: 'VAS',
    country: 'Brazil',
    founded: 1898,
    logo: 'https://media-2.api-sports.io/football/teams/133.png',
  },
  {
    id: 135,
    name: 'Cruzeiro',
    code: 'CRU',
    country: 'Brazil',
    founded: 1921,
    logo: 'https://media-1.api-sports.io/football/teams/135.png',
  },
  {
    id: 137,
    name: 'Figueirense',
    code: 'FIG',
    country: 'Brazil',
    founded: 1921,
    logo: 'https://media-1.api-sports.io/football/teams/137.png',
  },
  {
    id: 139,
    name: 'Ponte Preta',
    code: 'PON',
    country: 'Brazil',
    founded: 1900,
    logo: 'https://media-3.api-sports.io/football/teams/139.png',
  },
  {
    id: 144,
    name: 'Atletico Goianiense',
    code: 'ATL',
    country: 'Brazil',
    founded: 1937,
    logo: 'https://media-2.api-sports.io/football/teams/144.png',
  },
  {
    id: 147,
    name: 'Coritiba',
    code: 'COR',
    country: 'Brazil',
    founded: 1909,
    logo: 'https://media-2.api-sports.io/football/teams/147.png',
  },
  {
    id: 755,
    name: 'Nautico Recife',
    code: 'NAU',
    country: 'Brazil',
    founded: 1901,
    logo: 'https://media-1.api-sports.io/football/teams/755.png',
  },
  {
    id: 1062,
    name: 'Atletico-MG',
    code: 'ATL',
    country: 'Brazil',
    founded: 1908,
    logo: 'https://media-1.api-sports.io/football/teams/1062.png',
  },
  {
    id: 1214,
    name: 'Portuguesa',
    code: 'POR',
    country: 'Brazil',
    founded: 1920,
    logo: 'https://media-2.api-sports.io/football/teams/1214.png',
  },
];
